-- Corrected SQL using USERS tablespace (recommended approach)

-- First table (non-partitioned)
CREATE TABLE SALES_DATA (
    PRODUCT_ID      NUMBER,
    SALES_YEAR      NUMBER(4),
    COUNTRY         VARCHAR2(50),
    SALES_AMOUNT    NUMBER(12,2),
    QUANTITY        NUMBER,
    CONSTRAINT PK_SALES_DATA PRIMARY KEY (PRODUCT_ID, SALES_YEAR, COUNTRY)
) TABLESPACE USERS;

INSERT INTO SALES_DATA VALUES (101, 2022, 'USA', 150000, 1200);
INSERT INTO SALES_DATA VALUES (101, 2023, 'UK', 120000, 850);
INSERT INTO SALES_DATA VALUES (102, 2022, 'India', 90000, 2000);
INSERT INTO SALES_DATA VALUES (102, 2023, 'Germany', 110000, 1750);
COMMIT;

-- Second table (partitioned) - Using USERS tablespace
CREATE TABLE SALES_DATA_RANGE (
    PRODUCT_ID      NUMBER,
    SALES_YEAR      NUMBER(4),
    COUNTRY         VARCHAR2(50),
    SALES_AMOUNT    NUMBER(12,2),
    QUANTITY        NUMBER
)
PARTITION BY RANGE (SALES_YEAR) (
    PARTITION p2022 VALUES LESS THAN (2023) TABLESPACE USERS,
    PARTITION p2023 VALUES LESS THAN (2024) TABLESPACE USERS,
    PARTITION p2024 VALUES LESS THAN (2025) TABLESPACE USERS
);

INSERT INTO SALES_DATA_RANGE VALUES (101, 2022, 'USA', 150000, 1200);
INSERT INTO SALES_DATA_RANGE VALUES (101, 2023, 'UK', 120000, 850);
INSERT INTO SALES_DATA_RANGE VALUES (102, 2022, 'India', 90000, 2000);
INSERT INTO SALES_DATA_RANGE VALUES (102, 2023, 'Germany', 110000, 1750);
COMMIT;

-- Verify data
SELECT 'SALES_DATA' as table_name, COUNT(*) as row_count FROM SALES_DATA
UNION ALL
SELECT 'SALES_DATA_RANGE', COUNT(*) FROM SALES_DATA_RANGE;

-- Verify partitions
SELECT table_name, partition_name, high_value, tablespace_name
FROM user_tab_partitions
WHERE table_name = 'SALES_DATA_RANGE'
ORDER BY partition_position;
